monolog:
    channels: ['stripe']
    handlers:
        main:
            channels: ["!event", "!stripe"]
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        stripe:
            channels: ["stripe"]
            type: stream
            path: "%kernel.logs_dir%/stripe.log"
            level: error
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
