parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $stripeLogger: '@monolog.logger.stripe'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Client\StripeClient:
        arguments:
            $stripeSecretKey: '%env(resolve:STRIPE_API_KEY)%'

    App\Controller\StripeController:
        arguments:
            $stripeClientId: '%env(resolve:STRIPE_CLIENT_ID)%'

    App\ApiConnector\FirebaseConnector:
        arguments:
            $apiKey: '%env(FIREBASE_API_KEY)%'